SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_COLOR = "black"
SCORE_BAR_HEIGHT = 40
SCORE_FONT_SIZE = 30
SCORE_BAR_HORIZONTAL_PADDING = 30
SCORE_BAR_VERTICAL_PADDING = 10
SCORE_BAR_COLOR = "darkslategray"
SCORE_TEXT_COLOR = "white"
GAME_TOP_BOUNDARY = SCORE_BAR_HEIGHT

PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_LIVES = 3
PLAYER_RESPAWN_INVINCIBILITY_SECONDS = 2

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_RAPID_SHOT_DURATION_SECONDS = 10

POWERUP_SIDE_SIZE = ASTEROID_MIN_RADIUS * 2
POWERUP_RADIUS = POWERUP_SIDE_SIZE / 2
POWERUP_COLOR = "purple"
POWERUP_TEXT_COLOR = "white"
POWERUP_SCORE_INTERVAL = 30
